apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-edge-certs-pvc
  namespace: ferentin-service-edge
  labels:
    app.kubernetes.io/name: service-edge
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-edge-policy-pvc
  namespace: ferentin-service-edge
  labels:
    app.kubernetes.io/name: service-edge
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
