{{- if .Values.persistence.certs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "service-edge.fullname" . }}-certs
  labels:
    {{- include "service-edge.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.certs.accessMode }}
  {{- if .Values.persistence.certs.storageClass }}
  storageClassName: {{ .Values.persistence.certs.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.certs.size }}
{{- end }}
---
{{- if .Values.persistence.policy.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "service-edge.fullname" . }}-policy
  labels:
    {{- include "service-edge.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.policy.accessMode }}
  {{- if .Values.persistence.policy.storageClass }}
  storageClassName: {{ .Values.persistence.policy.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.policy.size }}
{{- end }}
