apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-edge.fullname" . }}-secrets
  labels:
    {{- include "service-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  edge-id: {{ .Values.config.edgeId | quote }}
  tenant-id: {{ .Values.config.tenantId | quote }}
  {{- if .Values.config.caBundle }}
  ca-bundle: {{ .Values.config.caBundle | quote }}
  {{- end }}
