apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-edge.fullname" . }}-secrets
  labels:
    {{- include "service-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.bootstrap.enrollmentToken }}
  enrollment-token: {{ .Values.config.bootstrap.enrollmentToken | quote }}
  {{- end }}
  {{- if .Values.config.caBundle }}
  ca-bundle: {{ .Values.config.caBundle | quote }}
  {{- end }}
