apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-edge.fullname" . }}
  labels:
    {{- include "service-edge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.tls.enabled }}
    - port: {{ .Values.service.tlsPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "service-edge.selectorLabels" . | nindent 4 }}
